version: "3"
services:

  client:
    build:
      context: ./
      dockerfile: client.Dockerfile
    command: ["./wait-for", "api:3000", "--", "npm", "run", "serve"]
    depends_on:
      - api
    ports:
    - 8080:8080
    volumes:
      - ./client/src:/workdir/app/client/src
      - ./api-dist:/workdir/app/api-dist

  api:
    build:
      context: ./
      dockerfile: api.Dockerfile
    command: npm run start:debug
    environment:
      MONGODB_URI: 'mongodb://mongodb:27017/shoppingList'
    depends_on:
      - mongodb
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./api/src:/app/api/src
      - ./api-dist:/app/api-dist

  mongodb:
    logging:
      driver: none
    image: mongo:4.2.7-bionic
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
