version: "3"
services:

  client:
    build:
      context: ./
      dockerfile: client.prod.Dockerfile
      args:
        API_URL: 'https://shoppinglist.jonasleitner.de'
        API_PATH: '/api'
    depends_on:
      - api
    ports:
    - 127.0.0.1:8080:8080

  api:
    build:
      context: ./
      dockerfile: api.prod.Dockerfile
    command: ["node", "/app/api-dist/dist/main"]
    environment:
      MONGODB_URI: 'mongodb://mongodb:27017/shoppingList'
      API_URL: 'https://shoppinglist.jonasleitner.de'
      API_PATH: '/api'
    depends_on:
      - mongodb
    ports:
      - 127.0.0.1:3000:3000

  mongodb:
    logging:
      driver: none
    image: mongo:4.2.7-bionic
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - /var/lib/mongodb:/data/db