version: "3"
services:

  client:
    build:
      context: ./
      dockerfile: client.prod.Dockerfile
    environment:
      API_URL: 'http://shoppinglist.jonasleitner.de/api'
    depends_on:
      - api
    ports:
    - 8080:8080

  api:
    build:
      context: ./
      dockerfile: api.prod.Dockerfile
    command: ["node", "/app/api-dist/dist/main"]
    environment:
      MONGODB_URI: 'mongodb://0.0.0.0:27017/shoppingList'
      API_URL: 'http://shoppinglist.jonasleitner.de/api'
    ports:
      - 3000:3000